### ISSUE TITLE
Errors in the "Error List window" do not go to the correct line number

### ISSUE THREAD

**Issue by boedlen** [JoshuaKGoldberg/TSLint.MSBuild#30]
When double clicking an error in the "Error List window" in Visual Studio 2015, you are taken to the correct file, but not the correct line number and character.

The line number actually shows up correctly in the `Line` column in the "Error List window", but I'm not taken to the correct line number when clicking. 
Double clicking the line from the "Output window" takes me to the correct line and character.

Is anyone else seeing this behavior?

**Comment by JoshuaKGoldberg** [comment]
I'm not able to reproduce the behavior in a new solution. Would you be able to upload the smallest size solution that repros here?

Also, what OS version and VS version are you using specifically? Update 1 / 2?

**Comment by esampsonite** [comment]
The PR https://github.com/JoshuaKGoldberg/TSLint.MSBuild/pull/36 should fix this issue.  I ran across this issue myself and dug into it a little deeper.  The crux of the issue was only the first forward slash in the file path was being converted to a backslash.  Once all of them were changed to backslashes, the problem was rectified.

**Comment by JoshuaKGoldberg** [comment]
Great!
