### ISSUE TITLE
Run with latest tslint

### ISSUE THREAD

**Issue by jonaskello** [JoshuaKGoldberg/TSLint.MSBuild#40]
First, nice work on this! Now a question, at this time the latest tslint available on nuget is 3.7.4 as far as I can see. I would like use a later version of tslint, for example 3.11.0 which is the current version on github. I guess the correct way would be for TSLint 3.11.0 to be published to nuget. Just wanted to check if there is a workaround to force TSLint.MSBuild to use 3.11.0 while waiting for them to publish that version to nuget?

**Comment by JoshuaKGoldberg** [comment]
Thanks :)

Funny enough, *I'm* the one who publishes TSLint to NuGet. 3.11.0 has been pushed to nuget.org as of five minutes ago. Can you check it and confirm here it works as expected?Since 3.7.4 there have been some changes to how the TypeScript peer dependency works; if those break things for you, we can work on ways around them.

If you end up waiting for a newer version in the future there are three things you can do:
* Use [https://github.com/JoshuaKGoldberg/tslint-nuget](tslint-nuget) to make the package yourself and manually copy it to your `packages` folder or equivalent. This only really works for local testing.
* Contact me to upload the package by email or opening another issue here.
* Upvote https://github.com/palantir/tslint/issues/1017

**Comment by jonaskello** [comment]
I guess I was lucky to ask in the right place then :-). I can verity that the new nuget package works as expected. Thanks for the update and info!
