### ISSUE TITLE
Remove the hardcoded TSLint dependency

### ISSUE THREAD

**Issue by stephen-nba** [JoshuaKGoldberg/TSLint.MSBuild#50]
Hi

Currently the NuGet package has a dependency on the TSLint NuGet package which has a whole bunch of npm packages going on, but in a different place to my projects other NPM modules. I'd prefer if I could use my regular node_modules folder that I already have in my project.

Is it possible to decouple the MSBuild NuGet from TSLint and use a custom TSLint folder that I can manage with NPM and no NuGet?

Thanks

Stephen

**Comment by JoshuaKGoldberg** [comment]
Yes. As per the [readme's section on properties](https://github.com/joshuakgoldberg/tslint.msbuild#overrideable-properties), you can specify a path to the TSLint CLI via `TSLintCli`.

```xml
<PropertyGroup>
    <TSlintCli>path/to/tslint/cli/tslint-cli.js</TSLintCli>
</PropertyGroup>
```

See https://github.com/JoshuaKGoldberg/TSLint.MSBuild/blob/master/test/TSLintCli/TSlintCli/TSLintCli.csproj for a working example.

I'll rename this issue to reference removing the hard TSLint dependency, since it's no longer required.
